### ISSUE TITLE
batch-tiling: Source and Destination Image via absolute path

### ISSUE THREAD

**Issue by cree321** [hits-sdo/hits-sdo-packager#26]
Hey @campjake !
I'm getting a similar error as [last time](https://github.com/hits-sdo/hits-sdo-packager/pull/25#pullrequestreview-1421787342) running the `tile_items.py` script . Sorry I cannot go as in depth this time - I'll try to find a solution tomorrow.

Error:
> Traceback (most recent call last):

>  File "c:\Users\trazm\Documents\hits-sdo-packager-batch-tiling\hits-sdo-packager\src\transformations\tile_items.py", line 280, in \<module>
    tc.cut_subset_tiles()

>  File "c:\Users\trazm\Documents\hits-sdo-packager-batch-tiling\hits-sdo-packager\src\transformations\tile_items.py", line 163, in cut_subset_tiles
    temp_image.save(tile_f_name.replace(" ", ""), "JPEG")

>  File "C:\Users\trazm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PIL\Image.py", line 2429, in save
    fp = builtins.open(filename, "w+b")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/trazm/Documents/hits-sdo-packager-batch-tiling/hits-sdo-packager/data/pre-processed\\20100905_000036_aia.lev1_euv_12s_4k/tiles/Users/trazm/Documents/hits-sdo-packager-batch-tiling/hits-sdo-packager/data/raw\\20100905_000036_aia.lev1_euv_12s_4k_tile_256_256.jpg'

**Comment by cree321** [comment]
Resolved. Good work, @amunozj  and @campjake !
